### ISSUE TITLE
cannnot locate cuda/cuda_config.h with binary installed tensorflow.

### ISSUE THREAD

**Issue by JiamingSuen** [Zardinality/TF_Deformable_Net#1]
cannnot locate cuda/cuda_config.h with binary installed tensorflow when compiling `deform_conv.cc`. I tried to locate `cuda_config.h` with `sudo find / -name cuda_config.h` and yield nothing. I suspect `cuda_config.h` file is only available when compiled from source, generated from [this template](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda/cuda_config.h.tpl). Do you use self-complied tf?

``` bash
➜  deform_conv_layer git:(master) ✗ g++ -std=c++11 -shared -o deform_conv.so deform_conv.cc deform_conv.cu.o -I$TF_INC -fPIC -lcudart -L$CUDA_PATH/lib64 -DGOOGLE_CUDA=1 -Wfatal-errors -D_GLIBCXX_USE_CXX11_ABI=0
In file included from /home/jiamingsun/anaconda3/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/platform/default/stream_executor.h:26:0,
                 from /home/jiamingsun/anaconda3/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/platform/stream_executor.h:24,
                 from deform_conv.cc:41:
/home/jiamingsun/anaconda3/lib/python3.6/site-packages/tensorflow/include/tensorflow/stream_executor/dso_loader.h:32:30: fatal error: cuda/cuda_config.h: No such file or directory
compilation terminated.

```

BTW there's a typo in `make.sh`
https://github.com/Zardinality/TF_Deformable_Net/blob/master/lib/make.sh#L45
Where `$CUDA_HOME` should be `$CUDA_PATH`, so as the followed instances.

Thanks!

**Comment by Zardinality** [comment]
Sorry for my neglection on the header stuff, last day in another repo someone file an [issue](https://github.com/Zardinality/TF-deformable-conv/issues/1) about it, so I change README of it to add a reminder. But I forgot this repo. How I wish could get rid of this include! But I have to use cublas and allocate gpu memory in `deform_conv.cc`.

If I am right, `cuda_config.h` should be placed in `$TF_INC/tensorflow/stream_executor/cuda` and the simplest method to repair it is to copy the header to this path in `make.sh`. What do you think?

**Comment by bwuzhang** [comment]
I copied [https://github.com/tensorflow/tensorflow/blob/master/third_party/toolchains/gpus/cuda/cuda/cuda_config.h](url) to $ROOT_PYTHON/site-packages/tensorflow/include/cude/cuda_config.h. It works for me.

**Comment by JiamingSuen** [comment]
Followed your solution the problem is resolved with:
```
cd `python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())'`
mkdir cuda; cd cuda;
curl -O https://raw.githubusercontent.com/tensorflow/tensorflow/master/third_party/toolchains/gpus/cuda/cuda/cuda_config.h
```

@Zardinality well for your modification for `make.sh` in a0f9e94d799554b1d59f582c7bde7aa554276a2d it didn't resolve the problem entirely since you used both `CUDA_HOME` and `CUDA_PATH` in the script.
