### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ghost** [Zardinality/TF_Deformable_Net#24]
@leinxx   @Zardinality @JiahuiYu 
At the beginning, these two errors appear.
![image](https://user-images.githubusercontent.com/33537489/46053171-53bc0c00-c174-11e8-805d-9c649f30f4d1.png)

After changing the two header files, the following error occurs
![image](https://user-images.githubusercontent.com/33537489/46053206-6cc4bd00-c174-11e8-89c9-39fa51132bc4.png)
This problem has puzzled me for a long time. Is there any suggestion? Thank you.

**Comment by knmac** [comment]
I think it's because your Tensorflow include the file `cuda.h` in this manner:
```
#include "cuda/include/cuda.h"
```
You can try to make the file visible by adding `cuda/include` in your `LD_LIBRARY_PATH` and include `cuda.h` instead.

For `nsync_cv.h` problem, try to use the flag `-I $NSYNC_INC` in `g++` commands to include the path.

Also, it looks like you're using Python 2.7. I think it works better with Python 3

**Comment by ghost** [comment]
@knmac 
Thank you for your advice, I have solved the previous problem ,mainly the latter error : 

4 errors detected in the compilation of "/tmp/tmpxft_00005a43_000000007_deform_psroi_pooling_op_gpu.cu.cpp1.ii".
g++: error: deform_psroi_pooling_op.cu.o: No such file or directory

**Comment by yfnn** [comment]
Have you solved this issue?

**Comment by ghost** [comment]
@yfnn   
I didn't solve this problem, can't find a solution

**Comment by yfnn** [comment]
那你实现可变性卷积了吗

**Comment by yfnn** [comment]
那你实现可变形卷积了吗

**Comment by YZ-510** [comment]
> @leinxx @Zardinality @JiahuiYu
> At the beginning, these two errors appear.
> ![image](https://user-images.githubusercontent.com/33537489/46053171-53bc0c00-c174-11e8-805d-9c649f30f4d1.png)
> 
> After changing the two header files, the following error occurs
> ![image](https://user-images.githubusercontent.com/33537489/46053206-6cc4bd00-c174-11e8-89c9-39fa51132bc4.png)
> This problem has puzzled me for a long time. Is there any suggestion? Thank you.
How to solve the problem in the first picture？I have the same problem，thank you。

**Comment by YinZ-510** [comment]
I compiled successfully with gcc-4.9 and g++-4.9, no error.

**Comment by ccnankai** [comment]
@yfnn 
我编译通过了，在ubuntu gcc5  python3

**Comment by YinZ-510** [comment]
> Have you solved this issue?
cd deform_psroi_pooling_layer
nvcc -std=c++11 -ccbin=/usr/bin/g++-4.9 -c -o deform_psroi_pooling_op.cu.o deform_psroi_pooling_op_gpu.cu.cc \
	-I $TF_INC -I $NSYNC_INC -I /usr/local -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -L /usr/local/cuda-8.0/lib64/ --expt-relaxed-constexpr -arch=$ARCH
把 -D GOOGLE_CUDA  换成 -L /usr/local/cuda-8.0/lib64/

**Comment by yfnn** [comment]
@YZ-510
I still have one issue as follows.
g++: error: deform_conv.cu.o: No such file or directory

I use familiar command "nvcc -std=c++11 -ccbin=/usr/bin/g++-7 -c -o deform_conv.cu.o deform_conv.cu.cc" to solve the first issue, but there are some errors like this,
In file included from deform_conv.cu.cc:68:0:
deform_conv.h:66:10: fatal error: third_party/eigen3/unsupported/Eigen/CXX11/Tensor: No such file or directory
#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

How can I solve this?

**Comment by YZ-510** [comment]
It's my make.sh, I use gcc-4.9 and g++-4.9:
nvcc -std=c++11 -ccbin=/usr/bin/g++-4.9 -c -o deform_conv.cu.o deform_conv.cu.cc -I $TF_INC -I $NSYNC_INC -I /usr/local -D\
          GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -L /usr/local/cuda-8.0/lib64/ --expt-relaxed-constexpr -arch=$ARCH
## if you install tf using already-built binary, or gcc version 4.x, uncomment the three lines below
g++-4.9 -std=c++11 -shared -o deform_conv.so deform_conv.cc deform_conv.cu.o -I\
      $TF_INC -I $NSYNC_INC -fPIC -lcudart -L $CUDA_HOME/lib64 -D GOOGLE_CUDA=1 -Wfatal-errors \
      -I$CUDA_HOME/include -L $TF_LIB -ltensorflow_framework -D_GLIBCXX_USE_CXX11_ABI=0

**Comment by YinZ-510** [comment]
@yfnn It's my make.sh, I use gcc-4.9 and g++-4.9:
nvcc -std=c++11 -ccbin=/usr/bin/g++-4.9 -c -o deform_conv.cu.o deform_conv.cu.cc -I $TF_INC -I $NSYNC_INC -I /usr/local -D\
          GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -L /usr/local/cuda-8.0/lib64/ --expt-relaxed-constexpr -arch=$ARCH
g++-4.9 -std=c++11 -shared -o deform_conv.so deform_conv.cc deform_conv.cu.o -I\
      $TF_INC -I $NSYNC_INC -fPIC -lcudart -L $CUDA_HOME/lib64 -D GOOGLE_CUDA=1 -Wfatal-errors \
      -I$CUDA_HOME/include -L $TF_LIB -ltensorflow_framework -D_GLIBCXX_USE_CXX11_ABI=0

**Comment by appyfizzA** [comment]
@YZ-510  I am using g++-4.9, and on doing make in terminal, I am getting the following error: 

**python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'utils/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
rm -rf build
sh make.sh
/usr/local/lib/python2.7/dist-packages/tensorflow/include
deform_psroi_pooling_op_gpu.cu.cc:15:0: warning: "CUDA_1D_KERNEL_LOOP" redefined
 #define CUDA_1D_KERNEL_LOOP(i, n)                            \
 ^
In file included from deform_psroi_pooling_op_gpu.cu.cc:10:0:
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/util/cuda_kernel_helper.h:30:0: note: this is the location of the previous definition
 #define CUDA_1D_KERNEL_LOOP(i, n) \
 ^
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/util/cuda_device_functions.h(523): error: calling a constexpr __host__ function("real") from a __device__ function("CudaAtomicAdd") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/util/cuda_device_functions.h(524): error: calling a constexpr __host__ function("imag") from a __device__ function("CudaAtomicAdd") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/util/cuda_device_functions.h(530): error: calling a constexpr __host__ function("real") from a __device__ function("CudaAtomicAdd") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/util/cuda_device_functions.h(531): error: calling a constexpr __host__ function("imag") from a __device__ function("CudaAtomicAdd") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(57): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(304): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(305): warning: integer conversion resulted in a change of sign

deform_psroi_pooling_op_gpu.cu.cc(172): warning: variable "transSize" was declared but never referenced

4 errors detected in the compilation of "/tmp/tmpxft_0000248b_00000000-7_deform_psroi_pooling_op_gpu.cu.cpp1.ii".
g++: error: deform_psroi_pooling_op.cu.o: No such file or directory
/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(57): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(304): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(305): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(57): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(304): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(305): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/generated_message_reflection.h(685): warning: variable "unused" was set but never used**

**Comment by aditipanda** [comment]
/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(57): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(304): warning: integer conversion resulted in a change of sign

/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(305): warning: integer conversion resulted in a change of sign

deform_psroi_pooling_op_gpu.cu.cc(172): warning: variable "transSize" was declared but never referenced

4 errors detected in the compilation of "/tmp/tmpxft_000028eb_00000000-7_deform_psroi_pooling_op_gpu.cu.cpp1.ii".
g++: error: deform_psroi_pooling_op.cu.o: No such file or directory
/usr/local/lib/python2.7/dist-packages/tensorflow/include/google/protobuf/arena_impl.h(57): warning: integer conversion resulted in a change of sign



Did anyone solve this? @ccnankai @yfnn @YZ-510

**Comment by YinZ-510** [comment]
@appyfizzA 
nvcc -std=c++11 -ccbin=/usr/bin/g++-4.9 -c -o deform_psroi_pooling_op.cu.o deform_psroi_pooling_op_gpu.cu.cc 
-I $TF_INC -I $NSYNC_INC -I /usr/local -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -L /usr/local/cuda-8.0/lib64/ --expt-relaxed-constexpr -arch=$ARCH
Replace    -D GOOGLE_CUDA   with    -L /usr/local/cuda-8.0/lib64/

**Comment by aditipanda** [comment]
> @appyfizzA
> nvcc -std=c++11 -ccbin=/usr/bin/g++-4.9 -c -o deform_psroi_pooling_op.cu.o deform_psroi_pooling_op_gpu.cu.cc
> -I $TF_INC -I $NSYNC_INC -I /usr/local -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -L /usr/local/cuda-8.0/lib64/ --expt-relaxed-constexpr -arch=$ARCH
> Replace -D GOOGLE_CUDA with -L /usr/local/cuda-8.0/lib64/

Thank you, it ran without error.
